# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/raulm/Desktop/unball/UnBallSSLclient/PyQt/debug.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_debug_selector(object):
    def setupUi(self, debug_selector):
        debug_selector.setObjectName("debug_selector")
        debug_selector.resize(535, 392)
        self.box_all_robots = QtWidgets.QComboBox(debug_selector)
        self.box_all_robots.setGeometry(QtCore.QRect(180, 10, 151, 30))
        self.box_all_robots.setObjectName("box_all_robots")
        self.box_all_robots.addItem("")
        self.box_all_robots.addItem("")
        self.box_all_robots.addItem("")
        self.box_all_robots.addItem("")
        self.frame = QtWidgets.QFrame(debug_selector)
        self.frame.setGeometry(QtCore.QRect(10, 50, 511, 331))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")

        self.retranslateUi(debug_selector)
        QtCore.QMetaObject.connectSlotsByName(debug_selector)

    def retranslateUi(self, debug_selector):
        _translate = QtCore.QCoreApplication.translate
        debug_selector.setWindowTitle(_translate("debug_selector", "Form"))
        self.box_all_robots.setItemText(0, _translate("debug_selector", "Path Planning "))
        self.box_all_robots.setItemText(1, _translate("debug_selector", "State Machine"))
        self.box_all_robots.setItemText(2, _translate("debug_selector", "Connections - Vision"))
        self.box_all_robots.setItemText(3, _translate("debug_selector", "Connections - Sim"))
