# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/raulm/Desktop/unball/UnBallSSLclient/PyQt/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(627, 291)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(30, 20, 341, 243))
        self.frame.setMaximumSize(QtCore.QSize(400, 500))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.multicast_ip_input = QtWidgets.QLineEdit(self.frame)
        self.multicast_ip_input.setObjectName("multicast_ip_input")
        self.verticalLayout.addWidget(self.multicast_ip_input)
        self.vision_port_input = QtWidgets.QLineEdit(self.frame)
        self.vision_port_input.setObjectName("vision_port_input")
        self.verticalLayout.addWidget(self.vision_port_input)
        self.referee_ip_input = QtWidgets.QLineEdit(self.frame)
        self.referee_ip_input.setObjectName("referee_ip_input")
        self.verticalLayout.addWidget(self.referee_ip_input)
        self.referee_port_input = QtWidgets.QLineEdit(self.frame)
        self.referee_port_input.setObjectName("referee_port_input")
        self.verticalLayout.addWidget(self.referee_port_input)
        self.yellow_port_input = QtWidgets.QLineEdit(self.frame)
        self.yellow_port_input.setObjectName("yellow_port_input")
        self.verticalLayout.addWidget(self.yellow_port_input)
        self.blue_port_input = QtWidgets.QLineEdit(self.frame)
        self.blue_port_input.setObjectName("blue_port_input")
        self.verticalLayout.addWidget(self.blue_port_input)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 6, 1)
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.reset_button = QtWidgets.QPushButton(Dialog)
        self.reset_button.setGeometry(QtCore.QRect(420, 140, 151, 51))
        self.reset_button.setStyleSheet("QPushButton{\n"
"    border-radius: 3px;\n"
"    background: rgb(234, 239, 44);\n"
"    color: black;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(234, 239, 44, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(234, 239, 44, 40);\n"
"}")
        self.reset_button.setObjectName("reset_button")
        self.confirm_button = QtWidgets.QPushButton(Dialog)
        self.confirm_button.setGeometry(QtCore.QRect(420, 80, 151, 51))
        self.confirm_button.setStyleSheet("QPushButton{\n"
"    border-radius: 3px;\n"
"    background: rgb(0, 85, 255);\n"
"    color: white;\n"
"}\n"
"QPushButton:hover {\n"
"    background: rgba(0, 85, 255, 220);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: rgba(0, 85, 255, 200);\n"
"}")
        self.confirm_button.setObjectName("confirm_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "vision_port"))
        self.label_6.setText(_translate("Dialog", "blue_port"))
        self.label_3.setText(_translate("Dialog", "referee_ip"))
        self.label_5.setText(_translate("Dialog", "yellow_port"))
        self.label.setText(_translate("Dialog", "multicast_ip"))
        self.label_4.setText(_translate("Dialog", "referee_port"))
        self.reset_button.setText(_translate("Dialog", "Resetar Default"))
        self.confirm_button.setText(_translate("Dialog", "Confirmar"))
